//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace HobbyShop {
    
    
    public partial class ModelsView {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
=======
        protected global::System.Web.UI.HtmlControls.HtmlForm form2;
>>>>>>> 35b39c33e26a67b10b7779b029c4bbca2a1c7b43
    }
}
